language: python
python: 3.8
dist: xenial
sudo: true
install:
  - sudo apt-get update
  - sudo apt-get install linuxdoc-tools linuxdoc-tools-info binutils-mingw-w64-i686 gcc-mingw-w64-i686 sshpass cmake
  - python -m pip install --upgrade pip numpy setuptools wheel
  - python -m pip install rust cvxpy cython ddt stestr qiskit==0.24.1 pennylane==0.14.1
script:
  - mkdir _build && cd _build && cmake -DFPPOW=4 -DENABLE_COMPLEX_X2=OFF .. && make -j 8 all
  - cd .. && sudo rm -r _build
  - mkdir _build && cd _build && cmake -DFPPOW=6 .. && make -j 8 all
  - sudo make install
  - cd .. && sudo rm -r _build
  - mkdir _build && cd _build && cmake -DFPPOW=5 .. && make -j 8 all
  - ./unittest --layer-qunit --proc-stabilizer-qpager [mirror]
  - cd ../..
#  - git clone -b qrack_unit_tests https://github.com/vm6502q/ProjectQ.git && cd ProjectQ
#  - python -m pip install -r requirements.txt
#  - python setup.py install
#  - cd build && python -m pytest . && cd ..
  - git clone https://github.com/vm6502q/qiskit-qrack-provider.git && cd qiskit-qrack-provider
  - python -m pip install .
  - python -m stestr run
  - cd ..
#  - git clone https://github.com/XanaduAI/pennylane-pq.git && cd pennylane-pq
#  - python -m pip install .
#  - python -m pytest .
  - git clone https://github.com/vm6502q/pennylane-qiskit.git && cd pennylane-qiskit
  - python -m pip install .
  - python -m pytest .
  - cd ..
#  - git clone https://github.com/SoftwareQuTech/SimulaQron.git && cd SimulaQron
#  - python -m pip install .
#  - echo "import simulaqron" > simulaqron_tests.py && echo "simulaqron.tests()" >> simulaqron_tests.py
#  - python simulaqron_tests.py
